config/routes.rb
Rails.application.routes.draw do
  
  root to: "restaurants#home"
  resources :restaurants do 
    resources :reviews, only: [:new, :create]
    collection do
      get "top"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews, dependent: :destroy
    validates :name, :address, :phone_number, :category, presence: true
    validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] } 
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, :content, presence: true
  validates :rating, numericality: true
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

    before_action :find_restaurant, only: [:show, :edit, :update, :destroy]
    before_action :get_average_ratings, only: [:index, :top]

  def home
  end

  def top
  end

  def index
  end

  def show
    @review = Review.new
    @average_rating = []
    @restaurant.reviews.each do |review| 
      @average_rating << review.rating
    end
    @average_rating = @average_rating.sum / (@average_rating.length == 0 ? 1 :  @average_rating.length)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
    
  end

#   def edit
#   end

#   def update
#     @restaurant = Restaurant.update(restaurant_params)
#   end

#   def destroy
#     @restaurant.destroy
#   end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def get_average_ratings
    @restaurants = Restaurant.all
    @average_rating = Review.where(restaurant_id: @restaurants)
    .group(:restaurant_id)
    .average(:rating)
    .transform_values { |rating| rating.round(2) }
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :find_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
        redirect_to restaurant_path(@restaurant)
    else
        render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="container">
    <%= yield %>
   </div>
  </body>
</html>

app/views/restaurants/home.html.erb
<div class="banner-home">
    <div class="header-home">
        <h1>Rails Yelp CopyCat</h1>
        <p>The fastest way to satisfy your hunger</p>
        <%= link_to "Discover", restaurants_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/restaurants/index.html.erb
  <div class="navbar">
    <%= link_to "Top restaurants", top_restaurants_path, class: "btn btn-success" %>
    <h1>Restaurants near you</h1>
    <%= link_to "Add new restaurant", new_restaurant_path, class: "btn btn-primary" %>
  </div>

<div class="restaurants">
    <% @restaurants.each do |restaurant| %>
    <div class="card mb-3">
        <div class="d-flex" style="width: 540px;">
          <%= image_tag("https://loremflickr.com/240/240/#{["carbonara", "desserts","beer","vodka", "salad","pizza", "sushi", "waffle", "pasta", "sashimi", "bread", "sandwich"].sample}/all")%>
            <div class="card-body">
              <% average_rating = @average_rating[restaurant.id].to_i %>
              <% review = restaurant.reviews.first.content %>
              <div>
                <h5><%= link_to restaurant.name, restaurant_path(restaurant) %></h5>
                <div style="padding: 4px 0">
                  <% average_rating.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                  <% (5 - average_rating).times do %>
                    <i class="far fa-star"></i>
                  <% end %>
                </div>
              </div>
                <p><%= restaurant.address %></p>
                <p style="opacity: 0.6"><i class="far fa-comment-alt"></i>
                <% if review.split.length > 10 %>
                <em>"<%= review.split.first(10).join(" ") %>..."</em>
                <% else %>
                <em><%= review %></em>
                <% end %>
                <strong><%= link_to "more", restaurant_path(restaurant) %></strong></p>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="box">
    <h2>Add new restaurant</h2>

    <%= simple_form_for (@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, :collection => ["chinese", "italian", "japanese", "french", "belgian"]  %>
    <%= f.submit "Add Restaurant", class: "btn btn-primary" %>
    <% end %>

    <%= link_to "Back to Main page", restaurants_path, class: "btn btn-dark", style: "margin-top: 16px;" %>
</div>

app/views/restaurants/show.html.erb
<div class="banner">
  <div class="header">
    <h3><%= @restaurant.name %></h3>
     <% @average_rating.times do %>
       <i class="fas fa-star"></i>
     <% end %>
     <% (5 - @average_rating).times do %>
       <i class="far fa-star"></i>
     <% end %>
    <p><%= @restaurant.address %></p>
    <p><%= @restaurant.phone_number %></p>
  </div>
</div>
<div style="padding: 16px;">
  <h2>Review Highlights</h2>
</div>

<div class="d-flex">
  <div class="row">
   <div class="col-12">
    <ul class="list-group">
      <% @restaurant.reviews.each do |review| %>
        <li class="list-group-item">
          <% review.rating.times do %>
          <i class="fas fa-star"></i>
        <% end %>
        <% (5 - review.rating).times do %>
          <i class="far fa-star"></i>
        <% end %>
        <br>
          <%= review.content %>
        </li>
      <% end %>
    </ul>
   </div>
  </div>
  <div class="col-6">
    <%= render "reviews/form", restaurant: @restaurant, review: @review %>
  </div>
</div>

<%= link_to "Back to main", restaurants_path, class: "btn btn-primary", style: "margin: 16px 0px" %>

app/views/restaurants/top.html.erb
  <div class="navbar">
    <%= link_to "Back to Main", restaurants_path, class: "btn btn-dark" %>    
    <h1>Top Restaurants</h1>
    <%= link_to "Add new restaurant", new_restaurant_path, class: "btn btn-primary" %>
  </div>

<div class="restaurants">
  <% @restaurants.each do |restaurant| %>
    <% average_rating = @average_rating[restaurant.id].to_i   %>
    <% review = restaurant.reviews.first.content %>
      <% if average_rating >= 4 %>
        <div class="card mb-3">

        <div class="d-flex" style="width: 480px">
          <%= image_tag("https://loremflickr.com/180/180/#{["carbonara", "desserts","beer","vodka", "salad","pizza", "sushi", "waffle", "pasta", "sashimi", "bread", "sandwich"].sample}/all") %>
            <div class="card-body">
              <div style="display: flex; justify-content: space-between">
                <h5><%= link_to restaurant.name, restaurant_path(restaurant) %></h5>
                <div>
                  <% average_rating.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                  <% (5 - average_rating).times do %>
                    <i class="far fa-star"></i>
                  <% end %>
                </div>
              </div>
              <p><%= restaurant.address %></p>
              <p style="opacity: 0.6"><i class="far fa-comment-alt"></i>
                <% if review.split.length > 10 %>
                    <em>"<%= review.split.first(10).join(" ") %>..."</em>
                <% else %>
                    <em>"<%= review %>"</em>
                <% end %>
                    <strong><%= link_to "more", restaurant_path(restaurant) %></strong>
              </p>
            </div>
        </div>
      </div>
      <% end %>
  <% end %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [ restaurant, review ] do |f| %>
  <%= f.input :content, label: 'Review content', placeholder: "Review...", :input_html => {:style=> 'resize: none; height: 150px'} %>
  <div class="review-box">
    <%= f.input :rating, :collection => (0..5), default: "1" %>
    <%= f.submit "Submit review" , class: "btn btn-primary"%>
  </div>
<% end %>

app/views/reviews/new.html.erb
<div class="box">
  <h2>Leave a Review</h2>
  <%= render "form", restaurant: @restaurant, review: @review %>
</div>